### ISSUE TITLE
mount directory

### ISSUE THREAD

**Issue by hunterlong** [crazy-max/xgo#1]
How can I mount the current directory rather than being forced to use a repo URL? 

I have statically compiled assets, but xgo does not mount the current directory.

**Comment by crazy-max** [comment]
@hunterlong See https://github.com/crazy-max/ghaction-xgo/runs/664355568?check_suite_focus=true#step:3:14 as an example:

`/opt/hostedtoolcache/ghaction-xgo/0.3.2/x64/xgo -go 1.14.x -dest build -targets windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64 -v -buildmode default -ldflags -s -w /home/runner/work/ghaction-xgo/ghaction-xgo`
