### ISSUE TITLE
How does this compare to techknowlogick/xgo

### ISSUE THREAD

**Issue by makeworld-the-better-one** [crazy-max/xgo#14]
It looks like [that fork](https://github.com/techknowlogick/xgo) supports more platforms? I would be interested in hearing about the differences.

**Comment by crazy-max** [comment]
@makeworld-the-better-one 

* https://github.com/crazy-max/xgo/blob/master/CHANGELOG.md
* https://github.com/karalabe/xgo/compare/master...crazy-max:master
