### ISSUE TITLE
how  to reuse the mod cache?

### ISSUE THREAD

**Issue by Mainintowhile** [crazy-max/xgo#21]
without use docker, go mod would use the $GOPATH/pkg/mod/cache, I  haven't figure out how to config to surport it with docker yet.
so how to config to reuse the cache otherwise go download package everytime?

**Comment by Mainintowhile** [comment]
resolve by change the code

**Comment by crazy-max** [comment]
@Mainintowhile 

> resolve by change the code

Feel free to open a PR thanks
