### ISSUE TITLE
GLIBC_2.28' not found

### ISSUE THREAD

**Issue by libsgh** [crazy-max/xgo#24]
How can I specify the GCC version?

**Comment by crazy-max** [comment]
@libsgh glibc on the machine you are trying to run the binary is too old. You'll either need to update glibc on your machine or use a custom docker image with a recent one.

**Comment by drakkan** [comment]
Hi,

I have the same issue with sftpgo on arm64 (and likely on ppc64le too). I use the [xgo GitHub Action](https://github.com/crazy-max/ghaction-xgo) to cross build for arm64 and ppc64 and then I build deb/rpm using nfpm:

- sftpgo [2.0.2](https://github.com/drakkan/sftpgo/releases/tag/v2.0.2) works on ubuntu 18.04 (glibc 2.27) and later:
```
./sftpgo -v
SFTPGo 2.0.2-cebd069-2021-02-17T07:13:20Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable
```

- sftpgo [2.0.3](https://github.com/drakkan/sftpgo/releases/tag/v2.0.3) requires glibc 2.28 (buster version) and so it don't work anymore on ubuntu 18.04

```
./sftpgo -v
./sftpgo: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./sftpgo)
```

The only relevant difference in my build workflow is that 2.0.2 was cross built using Go 1.16.0  while 2.0.3 with Go 1.16.2. 

Ubuntu 18.04 is still supported. Is it possible to produce binaries compatible with this old glibc version again? Thank you

**Comment by libsgh** [comment]
> Hi,
> 
> I have the same issue with sftpgo on arm64 (and likely on ppc64le too). I use the [xgo GitHub Action](https://github.com/crazy-max/ghaction-xgo) to cross build for arm64 and ppc64 and then I build deb/rpm using nfpm:
> 
> * sftpgo [2.0.2](https://github.com/drakkan/sftpgo/releases/tag/v2.0.2) works on ubuntu 18.04 (glibc 2.27) and later:
> 
> ```
> ./sftpgo -v
> SFTPGo 2.0.2-cebd069-2021-02-17T07:13:20Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable
> ```
> 
> * sftpgo [2.0.3](https://github.com/drakkan/sftpgo/releases/tag/v2.0.3) requires glibc 2.28 (buster version) and so it don't work anymore on ubuntu 18.04
> 
> ```
> ./sftpgo -v
> ./sftpgo: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./sftpgo)
> ```
> 
> The only relevant difference in my build workflow is that 2.0.2 was cross built using Go 1.16.0 while 2.0.3 with Go 1.16.2.
> 
> Ubuntu 18.04 is still supported. Is it possible to produce binaries compatible with this old glibc version again? Thank you

Try to use other XGO docker images
[techknowlogick/xgo](https://hub.docker.com/r/techknowlogick/xgo)

**Comment by drakkan** [comment]
> > Hi,
> > I have the same issue with sftpgo on arm64 (and likely on ppc64le too). I use the [xgo GitHub Action](https://github.com/crazy-max/ghaction-xgo) to cross build for arm64 and ppc64 and then I build deb/rpm using nfpm:
> > 
> > * sftpgo [2.0.2](https://github.com/drakkan/sftpgo/releases/tag/v2.0.2) works on ubuntu 18.04 (glibc 2.27) and later:
> > 
> > ```
> > ./sftpgo -v
> > SFTPGo 2.0.2-cebd069-2021-02-17T07:13:20Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable
> > ```
> > 
> > 
> > 
> > * sftpgo [2.0.3](https://github.com/drakkan/sftpgo/releases/tag/v2.0.3) requires glibc 2.28 (buster version) and so it don't work anymore on ubuntu 18.04
> > 
> > ```
> > ./sftpgo -v
> > ./sftpgo: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./sftpgo)
> > ```
> > 
> > 
> > The only relevant difference in my build workflow is that 2.0.2 was cross built using Go 1.16.0 while 2.0.3 with Go 1.16.2.
> > Ubuntu 18.04 is still supported. Is it possible to produce binaries compatible with this old glibc version again? Thank you
> 
> Try to use other XGO docker images
> [techknowlogick/xgo](https://hub.docker.com/r/techknowlogick/xgo)

Thank you but I switched to [QEMU](https://github.com/drakkan/sftpgo/blob/main/.github/workflows/release.yml#L237). It is a bit slower to build but the produced binaries are ok, it is enough for my use case
