### ISSUE TITLE
Clang / SDK mismatch?

### ISSUE THREAD

**Issue by leaanthony** [crazy-max/xgo#28]
I'm getting these errors when cross compiling to darwin using the latest 1.16 docker image:
```
/osxcross/target/bin/../SDK/MacOSX11.1.sdk/usr/include/os/availability.h:105:33: note: expanded from macro 'API_UNAVAILABLE_END'
    #define API_UNAVAILABLE_END _Pragma("clang attribute pop")
```
I'd read it could be that the version of clang being used is too old to support new pragmas. Any ideas?

**Comment by leaanthony** [comment]
It's basically this issue: https://github.com/google/shaka-packager/issues/868

**Comment by leaanthony** [comment]
bump

**Comment by crazy-max** [comment]
Should work with the latest release.
