### ISSUE TITLE
xgo Aliyun

### ISSUE THREAD

**Issue by Ran-Xing** [crazy-max/xgo#72]
Hello, I wrote an Alibaba Cloud image container and software based on your xgo, please forgive me if I have offended you

[XRSec/xgo](https://github.com/XRSec/xgo)

**Comment by crazy-max** [comment]
That's fine but keep the [LICENSE file](https://github.com/crazy-max/xgo/blob/master/LICENSE) on your repo.

**Comment by Ran-Xing** [comment]
OK！ @crazy-max
