### ISSUE TITLE
It seems to increase the workload

### ISSUE THREAD

**Issue by Ran-Xing** [crazy-max/xgo#75]
Excuse me, will the image be cleaned up after every compilation?

```
sed -i "s|ghcr.io/crazy-max/xgo|registry.cn-hangzhou.aliyuncs.com/xrsec/xgo|g" xgo.go
```

I only modified this part

**Comment by crazy-max** [comment]
If you talk about the image layers, it will change after each upgrade as the base image is constantly updated when a new Go version is released.
